/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    events: Event;
    resources: Resource;
    'grants-and-awards': GrantsAndAward;
    media: Media;
    memories: Memory;
    categories: Category;
    tags: Tag;
    'board-members': BoardMember;
    sponsors: Sponsor;
    'educator-spotlights': EducatorSpotlight;
    newsletters: Newsletter;
    'timeline-events': TimelineEvent;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    'grants-and-awards': GrantsAndAwardsSelect<false> | GrantsAndAwardsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    memories: MemoriesSelect<false> | MemoriesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'board-members': BoardMembersSelect<false> | BoardMembersSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    'educator-spotlights': EducatorSpotlightsSelect<false> | EducatorSpotlightsSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    'timeline-events': TimelineEventsSelect<false> | TimelineEventsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'homepage-settings': HomepageSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'homepage-settings': HomepageSettingsSelect<false> | HomepageSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Share news, announcements, and updates with your community
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Post headline
   */
  title: string;
  /**
   * Short summary (1-2 sentences) - appears in previews and search
   */
  excerpt: string;
  /**
   * Hero image for this post
   */
  featuredImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  /**
   * Primary category
   */
  categories?: (number | Category)[] | null;
  /**
   * Add tags (type to search or create new)
   */
  tags?: (number | Tag)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Publication date - set future date to schedule
   */
  publishedDate: string;
  /**
   * Feature this post on the homepage
   */
  isFeatured?: boolean | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Upload photos, PDFs, and other files. These can be used throughout your website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility (required for images). Describe the image for screen readers.
   */
  alt: string;
  /**
   * Optional caption for this media item. Supports formatting.
   */
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tags are usually auto-created when typing. Manual creation is rarely needed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Tag name (e.g., grammar, vocabulary, culture)
   */
  name: string;
  /**
   * URL-friendly version (auto-generated)
   */
  slug: string;
  /**
   * Number of times this tag is used
   */
  usageCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage user accounts and permissions. Only Developers can create/delete users.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Full name (used throughout the CMS)
   */
  name: string;
  /**
   * Developer: Full access | Manager: Can manage content & settings | Editor: Can manage content only
   */
  role: 'developer' | 'manager' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage upcoming conferences, workshops, and community gatherings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Event name (e.g., "2025 Spring Congreso Educativo")
   */
  title: string;
  /**
   * URL-friendly version (auto-generated)
   */
  slug: string;
  /**
   * Describe what attendees can expect
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  eventType: 'conference' | 'workshop' | 'webinar' | 'networking' | 'cultural_event' | 'professional_development';
  /**
   * Event start date and time
   */
  startDate: string;
  /**
   * Event end date and time (optional)
   */
  endDate?: string | null;
  /**
   * How will attendees participate?
   */
  locationType: 'in-person' | 'virtual' | 'hybrid';
  /**
   * Venue name (e.g., Columbia University)
   */
  venueName?: string | null;
  /**
   * Physical address
   */
  address?: string | null;
  /**
   * General location description (e.g., "New York City, NY")
   */
  location?: string | null;
  /**
   * External registration URL (e.g., Eventbrite link)
   */
  registrationLink?: string | null;
  /**
   * Event flyer or promotional image
   */
  featuredImage?: (number | null) | Media;
  /**
   * Additional event photos (add after event happens)
   */
  galleryImages?: (number | Media)[] | null;
  /**
   * Feature this event on homepage
   */
  isFeatured?: boolean | null;
  eventStatus: 'upcoming' | 'ongoing' | 'completed' | 'cancelled';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Curate lesson plans, worksheets, and teaching materials
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  /**
   * Resource name
   */
  title: string;
  /**
   * URL-friendly version (auto-generated)
   */
  slug: string;
  /**
   * What it is and why it's useful (2-3 sentences)
   */
  summary: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * What type of resource is this?
   */
  resourceType:
    | 'lesson_plan'
    | 'worksheet'
    | 'assessment'
    | 'video'
    | 'article'
    | 'website'
    | 'professional_development'
    | 'curriculum_guide'
    | 'interactive_activity';
  /**
   * Is this a link to an external website or an uploaded file?
   */
  sourceType: 'external_link' | 'hosted_file';
  /**
   * Link to external resource
   */
  externalUrl?: string | null;
  /**
   * Upload PDF, Word doc, PowerPoint, or other file
   */
  hostedFile?: (number | null) | Media;
  /**
   * Who created this resource? (e.g., ACTFL, AATSP, Teachers Pay Teachers)
   */
  sourceOrganization?: string | null;
  /**
   * Organization logo (optional)
   */
  sourceOrganizationLogo?: (number | null) | Media;
  /**
   * Thumbnail or preview image for this resource
   */
  previewImage?: (number | null) | Media;
  /**
   * Primary category
   */
  category?: (number | null) | Category;
  /**
   * Add tags (type to search or create new)
   */
  tags?: (number | Tag)[] | null;
  /**
   * Who added this resource?
   */
  curator: number | User;
  /**
   * Select all grade levels this resource is appropriate for
   */
  gradeLevels?: ('prek' | 'elementary' | 'middle' | 'high' | 'college' | 'adult')[] | null;
  /**
   * Target language proficiency level (ACTFL scale)
   */
  languageLevel?:
    | (
        | 'novice_low'
        | 'novice_mid'
        | 'novice_high'
        | 'intermediate_low'
        | 'intermediate_mid'
        | 'intermediate_high'
        | 'advanced_low'
        | 'advanced_mid'
        | 'advanced_high'
        | 'heritage'
        | 'all'
      )
    | null;
  /**
   * Which language(s) does this resource focus on?
   */
  subjectFocus?: ('spanish' | 'portuguese' | 'both')[] | null;
  /**
   * What language is the resource content written in?
   */
  contentLanguage?: ('english' | 'spanish' | 'portuguese' | 'bilingual') | null;
  /**
   * Curriculum standards this resource aligns with (e.g., ACTFL World-Readiness Standards, Common Core, state standards)
   */
  standardsAlignment?: string | null;
  /**
   * Estimated time needed (e.g., "45 minutes", "2 class periods", "15 min video")
   */
  duration?: string | null;
  /**
   * File size (e.g., "2.5 MB", "15 MB")
   */
  fileSize?: string | null;
  /**
   * When was this external link last checked to ensure it still works?
   */
  lastVerified?: string | null;
  /**
   * Mark if this external link is broken or no longer available
   */
  isBrokenLink?: boolean | null;
  /**
   * Does accessing this resource require creating an account or logging in?
   */
  requiresLogin?: boolean | null;
  /**
   * Is there a cost associated with this resource?
   */
  cost?: ('free' | 'freemium' | 'paid') | null;
  /**
   * Feature this resource on the homepage
   */
  isFeatured?: boolean | null;
  /**
   * Number of times this resource has been viewed
   */
  viewsCount?: number | null;
  /**
   * Number of times this resource link has been clicked
   */
  clicksCount?: number | null;
  /**
   * Number of times hosted file has been downloaded
   */
  downloadsCount?: number | null;
  dateAdded: string;
  /**
   * Archive this resource (hidden from public view)
   */
  isArchived?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage grant and award opportunities for educators
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grants-and-awards".
 */
export interface GrantsAndAward {
  id: number;
  /**
   * Opportunity name
   */
  title: string;
  /**
   * URL-friendly version (auto-generated)
   */
  slug: string;
  /**
   * Detailed description of the opportunity
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Type of opportunity
   */
  opportunityType: 'grant' | 'award' | 'fellowship' | 'scholarship';
  /**
   * Organization providing this opportunity (e.g., ACTFL, NEH)
   */
  provider: string;
  /**
   * Provider organization logo
   */
  providerLogo?: (number | null) | Media;
  /**
   * Link to application or more information
   */
  applicationUrl: string;
  /**
   * Application deadline
   */
  deadline: string;
  /**
   * When winners/recipients will be announced
   */
  announcementDate?: string | null;
  /**
   * Award/grant amount (e.g., "$5,000" or "$1,000-$5,000")
   */
  awardAmount?: string | null;
  /**
   * Who is eligible to apply? (e.g., K-12 teachers, college professors)
   */
  eligibility?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Select all applicable audiences
   */
  targetAudience?:
    | ('k12' | 'college' | 'grad_students' | 'undergrad_students' | 'administrators' | 'researchers')[]
    | null;
  /**
   * Which language(s) does this opportunity focus on?
   */
  subjectFocus?: ('spanish' | 'portuguese' | 'both' | 'general')[] | null;
  /**
   * Primary category
   */
  category?: (number | null) | Category;
  /**
   * Add tags (type to search or create new)
   */
  tags?: (number | Tag)[] | null;
  /**
   * Image for this opportunity
   */
  featuredImage?: (number | null) | Media;
  /**
   * Who added this opportunity?
   */
  curator: number | User;
  /**
   * Current status of this opportunity
   */
  status: 'upcoming' | 'active' | 'closed' | 'awarded';
  /**
   * Feature this opportunity on the homepage
   */
  isFeatured?: boolean | null;
  /**
   * Number of times this has been viewed
   */
  viewsCount?: number | null;
  /**
   * Number of times application link was clicked
   */
  clicksCount?: number | null;
  dateAdded: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Share photo albums and memories from past events
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memories".
 */
export interface Memory {
  id: number;
  /**
   * Event/album name (e.g., "Spring Conference 2024")
   */
  title: string;
  /**
   * URL-friendly version (auto-generated)
   */
  slug: string;
  /**
   * Describe what happened at this event
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * When the event occurred
   */
  date: string;
  /**
   * Where the event took place (e.g., "New York City, NY")
   */
  location?: string | null;
  /**
   * Automatically extracted from date
   */
  year?: number | null;
  /**
   * Album cover image - this will represent the album
   */
  coverPhoto: number | Media;
  /**
   * Gallery photos - upload multiple images from the event
   */
  photos: (number | Media)[];
  /**
   * Photographer name for attribution (optional)
   */
  photographerCredit?: string | null;
  publicationStatus: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage current and past board member profiles
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members".
 */
export interface BoardMember {
  id: number;
  /**
   * Full name of the board member
   */
  name: string;
  /**
   * Role within the organization
   */
  role: 'president' | 'vice_president' | 'secretary' | 'treasurer' | 'board_member' | 'advisory_board' | 'emeritus';
  /**
   * Professional title (e.g., "Spanish Teacher")
   */
  title?: string | null;
  /**
   * School or institution name
   */
  school?: string | null;
  /**
   * Board member biography and background
   */
  bio: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Professional headshot
   */
  photo: number | Media;
  /**
   * Contact email address
   */
  email?: string | null;
  /**
   * Sort order (lower numbers appear first)
   */
  displayOrder?: number | null;
  /**
   * Number of years served on the board
   */
  yearsServed?: number | null;
  /**
   * Current status of board membership
   */
  memberStatus: 'active' | 'inactive';
  /**
   * Social media links as JSON (e.g., {"linkedin": "url", "twitter": "url"})
   */
  socialLinks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Recognize organizations and individuals supporting your mission
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  /**
   * Sponsor organization name
   */
  name: string;
  /**
   * Sponsorship tier level
   */
  tier: 'featured' | 'gold' | 'silver' | 'bronze' | 'partner';
  /**
   * Sponsor logo image
   */
  logo: number | Media;
  /**
   * Information about the sponsor organization
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Sponsor website URL
   */
  website?: string | null;
  /**
   * Primary contact person name
   */
  contactName?: string | null;
  /**
   * Primary contact email address
   */
  contactEmail?: string | null;
  /**
   * Monetary contribution amount (if applicable)
   */
  contributionAmount?: number | null;
  /**
   * Type of contribution provided
   */
  contributionType?: ('monetary' | 'in_kind' | 'services' | 'mixed') | null;
  /**
   * Start date of sponsorship
   */
  sponsorshipStart?: string | null;
  /**
   * End date of sponsorship (if applicable)
   */
  sponsorshipEnd?: string | null;
  /**
   * Whether this sponsor is currently active
   */
  isActive?: boolean | null;
  /**
   * Feature this sponsor on the homepage
   */
  displayOnHomepage?: boolean | null;
  /**
   * Sort order (lower numbers appear first)
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Highlight exceptional educators making a difference
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educator-spotlights".
 */
export interface EducatorSpotlight {
  id: number;
  /**
   * Teacher's full name
   */
  teacherName: string;
  /**
   * Professional title/role
   */
  role: string;
  /**
   * Grade levels taught (e.g., "6th-8th Grade")
   */
  gradesTaught: string;
  /**
   * Name of school or institution
   */
  schoolName: string;
  /**
   * Inspiring quote from the teacher (1-2 sentences)
   */
  quote: string;
  /**
   * Professional photo of the teacher
   */
  photo: number | Media;
  /**
   * First achievement badge (e.g., "15 Years Teaching")
   */
  badge1?: string | null;
  /**
   * Second achievement badge
   */
  badge2?: string | null;
  /**
   * Third achievement badge
   */
  badge3?: string | null;
  /**
   * Fourth achievement badge
   */
  badge4?: string | null;
  /**
   * Link to member profile if available
   */
  memberProfile?: (number | null) | User;
  /**
   * WARNING: Only ONE spotlight can be active at a time
   */
  featuredStatus: 'draft' | 'active' | 'archived';
  /**
   * Date when this spotlight was activated (auto-set)
   */
  featuredFrom?: string | null;
  /**
   * Date when this spotlight was archived (auto-set)
   */
  featuredUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Publish newsletters and periodic communications
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: number;
  /**
   * Newsletter title
   */
  title: string;
  /**
   * URL-friendly version (auto-generated)
   */
  slug: string;
  /**
   * Volume/issue number (e.g., "Vol 12, Issue 1")
   */
  issueNumber?: string | null;
  /**
   * Publication date
   */
  publishDate: string;
  /**
   * Brief description of the newsletter content
   */
  summary?: string | null;
  publicationStatus: 'draft' | 'published';
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Chronicle the organization's history with milestone events
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events".
 */
export interface TimelineEvent {
  id: number;
  /**
   * The primary year this event occurred
   */
  year: number;
  /**
   * Specific date if known (optional)
   */
  date?: string | null;
  /**
   * Event headline (e.g., "First Annual Conference")
   */
  title: string;
  /**
   * Tell the story of what happened
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Primary image for this timeline event
   */
  featuredImage: number | Media;
  /**
   * Additional images for this event (optional)
   */
  images?: (number | Media)[] | null;
  /**
   * Check this to highlight as a major milestone
   */
  isMilestone?: boolean | null;
  /**
   * Image display position on timeline
   */
  imagePosition?: ('left' | 'center' | 'right') | null;
  /**
   * Image size on timeline
   */
  imageSize?: ('small' | 'medium' | 'large') | null;
  /**
   * Order within the same year (lower numbers appear first)
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'grants-and-awards';
        value: number | GrantsAndAward;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'memories';
        value: number | Memory;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'board-members';
        value: number | BoardMember;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'educator-spotlights';
        value: number | EducatorSpotlight;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'timeline-events';
        value: number | TimelineEvent;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  tags?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedDate?: T;
  isFeatured?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  eventType?: T;
  startDate?: T;
  endDate?: T;
  locationType?: T;
  venueName?: T;
  address?: T;
  location?: T;
  registrationLink?: T;
  featuredImage?: T;
  galleryImages?: T;
  isFeatured?: T;
  eventStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  resourceType?: T;
  sourceType?: T;
  externalUrl?: T;
  hostedFile?: T;
  sourceOrganization?: T;
  sourceOrganizationLogo?: T;
  previewImage?: T;
  category?: T;
  tags?: T;
  curator?: T;
  gradeLevels?: T;
  languageLevel?: T;
  subjectFocus?: T;
  contentLanguage?: T;
  standardsAlignment?: T;
  duration?: T;
  fileSize?: T;
  lastVerified?: T;
  isBrokenLink?: T;
  requiresLogin?: T;
  cost?: T;
  isFeatured?: T;
  viewsCount?: T;
  clicksCount?: T;
  downloadsCount?: T;
  dateAdded?: T;
  isArchived?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grants-and-awards_select".
 */
export interface GrantsAndAwardsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  opportunityType?: T;
  provider?: T;
  providerLogo?: T;
  applicationUrl?: T;
  deadline?: T;
  announcementDate?: T;
  awardAmount?: T;
  eligibility?: T;
  targetAudience?: T;
  subjectFocus?: T;
  category?: T;
  tags?: T;
  featuredImage?: T;
  curator?: T;
  status?: T;
  isFeatured?: T;
  viewsCount?: T;
  clicksCount?: T;
  dateAdded?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memories_select".
 */
export interface MemoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  date?: T;
  location?: T;
  year?: T;
  coverPhoto?: T;
  photos?: T;
  photographerCredit?: T;
  publicationStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  usageCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members_select".
 */
export interface BoardMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  title?: T;
  school?: T;
  bio?: T;
  photo?: T;
  email?: T;
  displayOrder?: T;
  yearsServed?: T;
  memberStatus?: T;
  socialLinks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  tier?: T;
  logo?: T;
  description?: T;
  website?: T;
  contactName?: T;
  contactEmail?: T;
  contributionAmount?: T;
  contributionType?: T;
  sponsorshipStart?: T;
  sponsorshipEnd?: T;
  isActive?: T;
  displayOnHomepage?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educator-spotlights_select".
 */
export interface EducatorSpotlightsSelect<T extends boolean = true> {
  teacherName?: T;
  role?: T;
  gradesTaught?: T;
  schoolName?: T;
  quote?: T;
  photo?: T;
  badge1?: T;
  badge2?: T;
  badge3?: T;
  badge4?: T;
  memberProfile?: T;
  featuredStatus?: T;
  featuredFrom?: T;
  featuredUntil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  issueNumber?: T;
  publishDate?: T;
  summary?: T;
  publicationStatus?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events_select".
 */
export interface TimelineEventsSelect<T extends boolean = true> {
  year?: T;
  date?: T;
  title?: T;
  description?: T;
  featuredImage?: T;
  images?: T;
  isMilestone?: T;
  imagePosition?: T;
  imageSize?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage site-wide settings including contact info, social links, and analytics
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * The main title of your website
   */
  siteTitle: string;
  /**
   * A brief description of your website for SEO
   */
  siteDescription: string;
  /**
   * Primary contact email address
   */
  contactEmail: string;
  /**
   * Contact phone number
   */
  contactPhone?: string | null;
  /**
   * Physical address or mailing address
   */
  contactAddress?: string | null;
  /**
   * Social media links for the organization
   */
  socialLinks?:
    | {
        platform: 'facebook' | 'twitter' | 'instagram' | 'linkedin' | 'youtube' | 'tiktok' | 'other';
        /**
         * Full URL to your social media profile
         */
        url: string;
        /**
         * Optional custom label (defaults to platform name)
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  announcementBar?: {
    /**
     * Show/hide the announcement bar
     */
    enabled?: boolean | null;
    /**
     * Announcement message text
     */
    message?: string | null;
    /**
     * Optional link URL (e.g., /events or https://...)
     */
    link?: string | null;
    /**
     * Link button text (e.g., "Learn More")
     */
    linkText?: string | null;
    /**
     * Visual style of the announcement bar
     */
    style?: ('info' | 'success' | 'warning' | 'error') | null;
  };
  /**
   * Google Analytics tracking ID (e.g., G-XXXXXXXXXX)
   */
  googleAnalyticsId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Customize all aspects of your homepage including hero, quick stops, community sections, and footer
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings".
 */
export interface HomepageSetting {
  id: number;
  heroSection: {
    /**
     * Small accent text displayed above the main heading (keep under 5 words)
     */
    accentText?: string | null;
    /**
     * Main headline - aim for 8-12 words that capture your mission
     */
    headline: string;
    /**
     * Supporting text below the headline (2-3 sentences)
     */
    description?: string | null;
    /**
     * The main action button (typically more prominent visually)
     */
    primaryCTA?: {
      /**
       * Button text
       */
      label?: string | null;
      /**
       * Internal link (starts with /) or external URL (starts with https://)
       */
      link?: string | null;
    };
    /**
     * The secondary action button (typically less prominent)
     */
    secondaryCTA?: {
      /**
       * Button text
       */
      label?: string | null;
      /**
       * Internal link (starts with /) or external URL (starts with https://)
       */
      link?: string | null;
    };
    /**
     * Hero section background image (recommended: 1920x1080px, under 2MB)
     */
    backgroundImage: number | Media;
  };
  /**
   * Manage the quick access cards shown in the carousel. Cards appear in order from 1 to 5.
   */
  quickStops?: {
    /**
     * Highlight a chapter sponsor with their logo and description
     */
    featuredSponsor?: {
      /**
       * Toggle off to temporarily hide this card without losing your settings
       */
      enabled?: boolean | null;
      /**
       * Select which sponsor to feature. To manage sponsors, go to Collections → Sponsors.
       */
      sponsor?: (number | null) | Sponsor;
    };
    /**
     * 🔄 Auto-generated: Shows the next upcoming event from the Events collection
     */
    upcomingEvent?: {
      /**
       * Toggle off to temporarily hide this card without losing your settings
       */
      enabled?: boolean | null;
    };
    /**
     * Display a random resource or choose a specific one to feature
     */
    resourceCard?: {
      /**
       * Toggle off to temporarily hide this card without losing your settings
       */
      enabled?: boolean | null;
      /**
       * Random mode keeps content fresh automatically. Specific mode lets you pin an important resource.
       */
      displayMode?: ('random' | 'specific') | null;
      /**
       * Select a specific resource to display. To manage resources, go to Collections → Resources.
       */
      resource?: (number | null) | Resource;
    };
    /**
     * Display the latest news post or choose a specific one to feature
     */
    latestNews?: {
      /**
       * Toggle off to temporarily hide this card without losing your settings
       */
      enabled?: boolean | null;
      /**
       * Latest mode automatically shows your newest published post. Specific mode lets you pin an important announcement.
       */
      displayMode?: ('latest' | 'specific') | null;
      /**
       * Select a specific news post to display. To manage news posts, go to Collections → Posts.
       */
      newsPost?: (number | null) | Post;
    };
    /**
     * Display the latest newsletter with subscribe action
     */
    newsletter?: {
      /**
       * Toggle off to temporarily hide this card without losing your settings
       */
      enabled?: boolean | null;
      /**
       * Latest mode automatically shows your newest newsletter. Specific mode lets you pin an older issue.
       */
      displayMode?: ('latest' | 'specific') | null;
      /**
       * Select a specific newsletter to display. To manage newsletters, go to Collections → Newsletters.
       */
      selectedNewsletter?: (number | null) | Newsletter;
      primaryAction?: {
        /**
         * Button text
         */
        label?: string | null;
        /**
         * Link to subscription page or form
         */
        link?: string | null;
      };
    };
  };
  /**
   * This section highlights your community with 4 cards: educator spotlight, upcoming events preview, latest news preview, and chapter achievement statistics.
   */
  communityInAction?: {
    /**
     * Background image for the Community in Action section (recommended: 1920x1080px, under 2MB)
     */
    backgroundImage?: (number | null) | Media;
    /**
     * Feature a spotlight on an educator from your chapter
     */
    educatorSpotlight?: {
      /**
       * Toggle off to temporarily hide this card without losing your settings
       */
      enabled?: boolean | null;
      /**
       * Select which educator spotlight to feature. To manage spotlights, go to Collections → Educator Spotlights.
       */
      spotlight?: (number | null) | EducatorSpotlight;
    };
    /**
     * 🔄 Auto-generated: Displays the next 3 upcoming events from the Events collection
     */
    upcomingEventsPreview?: {
      /**
       * Toggle off to temporarily hide this card without losing your settings
       */
      enabled?: boolean | null;
    };
    /**
     * 🔄 Auto-generated: Displays the 3 most recent published posts from the Posts collection
     */
    latestNewsPreview?: {
      /**
       * Toggle off to temporarily hide this card without losing your settings
       */
      enabled?: boolean | null;
    };
    /**
     * Add 2-6 achievement statistics to highlight chapter accomplishments (e.g., number of members, events hosted, years of service)
     */
    chapterAchievements?:
      | {
          /**
           * The number or statistic
           */
          topText: string;
          /**
           * The label describing the statistic
           */
          bottomText: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Share your chapter's history and partnerships with 2 cards: a combined photos & timeline card, and a partners showcase featuring sponsors.
   */
  chapterStory?: {
    /**
     * Background image for the Chapter Story section (recommended: 1920x1080px, under 2MB)
     */
    backgroundImage?: (number | null) | Media;
    /**
     * 🔄 Auto-generated: Links to your photo gallery (Memories) and timeline content (Timeline Events)
     */
    photosTimeline?: {
      /**
       * Toggle off to temporarily hide this card without losing your settings
       */
      enabled?: boolean | null;
    };
    /**
     * Showcase your featured sponsor and partner organizations
     */
    partners?: {
      /**
       * Toggle off to temporarily hide this card without losing your settings
       */
      enabled?: boolean | null;
      /**
       * Choose the main featured sponsor for this section (displays prominently with description). To manage sponsors, go to Collections → Sponsors.
       */
      featuredSponsor?: (number | null) | Sponsor;
      /**
       * Select up to 5 partners to display in the grid below the featured sponsor (logos only)
       */
      partnerLogos?: (number | Sponsor)[] | null;
    };
  };
  /**
   * Configure your site footer with logo, description, social media links, contact info, copyright text, and legal links.
   */
  footer?: {
    /**
     * Logo image displayed in the footer (recommended: PNG with transparent background, max height 80px)
     */
    footerLogo?: (number | null) | Media;
    /**
     * Brief description or tagline displayed in the footer (1-2 sentences)
     */
    footerDescription?: string | null;
    /**
     * Add social media links for the footer
     */
    socialMediaLinks?:
      | {
          platform: 'facebook' | 'twitter' | 'instagram' | 'linkedin' | 'youtube' | 'tiktok' | 'other';
          /**
           * Full URL to your social media profile
           */
          url: string;
          /**
           * Optional custom label (defaults to platform name if left empty)
           */
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Contact details displayed in the footer
     */
    contactInfo?: {
      /**
       * Physical location or address (optional)
       */
      location?: string | null;
      /**
       * Toggle to show/hide the contact form button in the footer
       */
      showContactForm?: boolean | null;
      /**
       * Link to open contact form (internal page, modal, or external URL)
       */
      contactFormLink?: string | null;
    };
    /**
     * Copyright text displayed in the footer
     */
    copyrightText?: string | null;
    /**
     * Add legal and policy links (Privacy Policy, Terms of Service, etc.)
     */
    legalLinks?:
      | {
          /**
           * Link text
           */
          label: string;
          /**
           * Link URL
           */
          link: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  siteDescription?: T;
  contactEmail?: T;
  contactPhone?: T;
  contactAddress?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  announcementBar?:
    | T
    | {
        enabled?: T;
        message?: T;
        link?: T;
        linkText?: T;
        style?: T;
      };
  googleAnalyticsId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings_select".
 */
export interface HomepageSettingsSelect<T extends boolean = true> {
  heroSection?:
    | T
    | {
        accentText?: T;
        headline?: T;
        description?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              link?: T;
            };
        secondaryCTA?:
          | T
          | {
              label?: T;
              link?: T;
            };
        backgroundImage?: T;
      };
  quickStops?:
    | T
    | {
        featuredSponsor?:
          | T
          | {
              enabled?: T;
              sponsor?: T;
            };
        upcomingEvent?:
          | T
          | {
              enabled?: T;
            };
        resourceCard?:
          | T
          | {
              enabled?: T;
              displayMode?: T;
              resource?: T;
            };
        latestNews?:
          | T
          | {
              enabled?: T;
              displayMode?: T;
              newsPost?: T;
            };
        newsletter?:
          | T
          | {
              enabled?: T;
              displayMode?: T;
              selectedNewsletter?: T;
              primaryAction?:
                | T
                | {
                    label?: T;
                    link?: T;
                  };
            };
      };
  communityInAction?:
    | T
    | {
        backgroundImage?: T;
        educatorSpotlight?:
          | T
          | {
              enabled?: T;
              spotlight?: T;
            };
        upcomingEventsPreview?:
          | T
          | {
              enabled?: T;
            };
        latestNewsPreview?:
          | T
          | {
              enabled?: T;
            };
        chapterAchievements?:
          | T
          | {
              topText?: T;
              bottomText?: T;
              id?: T;
            };
      };
  chapterStory?:
    | T
    | {
        backgroundImage?: T;
        photosTimeline?:
          | T
          | {
              enabled?: T;
            };
        partners?:
          | T
          | {
              enabled?: T;
              featuredSponsor?: T;
              partnerLogos?: T;
            };
      };
  footer?:
    | T
    | {
        footerLogo?: T;
        footerDescription?: T;
        socialMediaLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              label?: T;
              id?: T;
            };
        contactInfo?:
          | T
          | {
              location?: T;
              showContactForm?: T;
              contactFormLink?: T;
            };
        copyrightText?: T;
        legalLinks?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}